
const LOADING = "LOADING"
const FETCHING_ERROR = "FETCHING_ERROR"
const DATA_RECEIVED = "DATA_RECEIVED"
const UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR"
const FILIERE_ON_DELETION_PROCCESS = "FILIERE_ON_DELETION_PROCCESS"
const FILIERE_ON_ADDING_PROCCESS ="FILIERE_ON_ADDING_PROCCESS"
const FILIERE_ON_UPDATING_PROCCESS="FILIERE_ON_UPDATING_PROCCESS"
const FILIERE_ADDING_ERROR = "FILIERE_ADDING_ERROR"
const UPDATE_ERROR="UPDATE_ERROR"
const DELETE_ERROR = "DELETE_ERROR"
const LOGIN__PROCCESS = "LOGIN__PROCCESS"
const LOGIN__SUCCESS = "LOGIN__SUCCESS"
const LOGIN__ERROR = "LOGIN__ERROR"
const LOGOUT ="LOGOUT"
const GET_LOCAL_TOKEN = "GET_LOCAL_TOKEN"

export {
  FETCHING_ERROR,
  FILIERE_ADDING_ERROR,
  UNAUTHORIZED_ERROR,
  UPDATE_ERROR,
  DELETE_ERROR,
  LOADING,
  FILIERE_ON_DELETION_PROCCESS,
  FILIERE_ON_ADDING_PROCCESS,
  FILIERE_ON_UPDATING_PROCCESS,
  DATA_RECEIVED,
  LOGIN__PROCCESS,
  LOGIN__SUCCESS,
  LOGIN__ERROR,
  LOGOUT,
  GET_LOCAL_TOKEN
}