
const LOADING = "LOADING"
const FETCHING_ERROR = "FETCHING_ERROR"
const DATA_RECEIVED = "DATA_RECEIVED"
const UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR"
const FILIERE_ON_DELETION_PROCCESS = "FILIERE_ON_DELETION_PROCCESS"
const FILIERE_ON_ADDING_PROCCESS ="FILIERE_ON_ADDING_PROCCESS"
const FILIERE_ADDING_ERROR = "FILIERE_ADDING_ERROR"
export {
  FETCHING_ERROR,
  FILIERE_ADDING_ERROR,
  UNAUTHORIZED_ERROR,
  LOADING,
  FILIERE_ON_DELETION_PROCCESS,
  FILIERE_ON_ADDING_PROCCESS,
  DATA_RECEIVED
}